config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'healthcheck', to: 'healthcheck#show'

  resources :organizations do
    resources :transactions
    resources :incomes
    resources :expenses
    resources :memberships
  end

  devise_for :users
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member, class_name: 'User', foreign_key: :user_id, inverse_of: :memberships, autosave: true
  belongs_to :organization
  has_many :incomes, dependent: :destroy

  delegate :name, :phone, to: :member, allow_nil: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_organization
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = policy_scope @organization.memberships
    authorize @organization, :memberships?
  end

  # GET /memberships/1 or /memberships/1.json
  def show
    authorize @membership, policy_class: MembershipPolicy
  end

  # GET /memberships/new
  def new
    @membership = Membership.new(
      organization: @organization
    )
    authorize @membership, policy_class: MembershipPolicy
  end

  # GET /memberships/1/edit
  def edit
    authorize @membership, policy_class: MembershipPolicy
  end

  # POST /memberships or /memberships.json
  def create
    Create.new(self, membership_params:, organization: @organization).call
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    Update.new(self, membership_params:, organization: @organization).call
    authorize @membership, policy_class: MembershipPolicy
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    authorize @membership, policy_class: MembershipPolicy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url, notice: t('membership_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:name, :phone)
  end

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: [@organization, membership]) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class: 'form-label' %>
    <%= form.text_field :phone, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.submit t('save'), class: 'btn btn-primary' %>
    <% if membership.new_record? %>
      <%= link_to t('cancel'), organization_path(@organization), class: 'btn btn-secondary' %>
    <% else %>
      <%= link_to t('cancel'), organization_membership_path(@organization, membership), class: 'btn btn-secondary' %>
    <% end %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Name:</strong>
    <%= membership.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= membership.phone %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

app/views/memberships/index.html.erb
<h1><%= t('members').capitalize %></h1>

<table class="table table-striped table-hover">
  <thead class="">
    <tr>
      <th><%= t('member_name') %></th>
      <th><%= t('phone') %></th>
      <th><%= t('role') %></th>
      <th><%= t('registered_at') %></th>
    </tr>
  </thead>
  <tbody  class="">
    <% @memberships.sort_by(&:name).each do |membership| %>
      <tr>
        <td><%= link_to membership.name, organization_membership_url(@organization, membership) %></td>
        <td><%= membership.phone %></td>
        <td><%= t "roles.#{membership.role}" %></td>
        <td><%= l membership.created_at.to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if policy(@organization).add_member? %>
  <%= link_to t('add_member'), new_organization_membership_path(@organization), class: 'btn btn-primary' %>
<% end %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", organization_memberships_url(@organization) %>
</div>

app/views/memberships/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @membership.name %></h1>

<table class="table  table-striped">
  <tr>
    <th><%= t('name') %></th>
    <td><%= @membership.name %></td>
  </tr>
  <tr>
    <th><%= t('phone') %></th>
    <td><%= @membership.phone %></td>
  </tr>
  <tr>
    <th><%= t('role') %></th>
    <td><%= t "roles.#{@membership.role}" %></td>
  </tr>
</table>


<% if policy(@membership).edit? %>
  <%= link_to t('edit'), edit_organization_membership_path(@organization, @membership), class: 'btn btn-primary' %>
<% end %>