config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'healthcheck', to: 'healthcheck#show'

  resources :organizations do
    resources :transactions
    resources :incomes
    resources :expenses
    resources :memberships
  end

  devise_for :users
end

app/models/income.rb
class Income < Transaction
  validates :amount, numericality: { greater_then: 0 }
  belongs_to :membership
  delegate :member, to: :membership

  def description = "#{member.name} #{comment}"
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[show edit update destroy]
  before_action :set_organization

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
    authorize IncomePolicy.new(current_user, :income, organization: @organization).index?
  end

  # GET /incomes/1 or /incomes/1.json
  def show
    authorize @income
  end

  class NewIncome < SimpleDelegator
    attr_reader :organization

    def initialize(income, organization:)
      super income
      @organization = organization
    end
  end

  # GET /incomes/new
  def new
    @income = NewIncome.new(
      Income.new,
      organization: @organization
    )
    authorize @income
  end

  # GET /incomes/1/edit
  def edit
    authorize @income
  end

  # POST /incomes or /incomes.json
  def create
    Create.new(
      income_params:,
      context: self
    ).call
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    authorize @income
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to organization_url(@organization), notice: t('income_updated') }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: t('income_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_income
    @income = Income.find(params[:id])
  end

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  # Only allow a list of trusted parameters through.
  def income_params
    params.require(:income).permit(:membership_id, :amount)
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: [@organization, income]) do |form| %>
  <% if income.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :membership_id, t('member').capitalize, class: 'form-label' %>
    <%= form.select :membership_id, @organization.memberships.map { |m| [m.name, m.id] }, { include_blank: true }, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, t('money_amount').capitalize, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <% if income.new_record? %>
      <%= form.submit t('add'), class: 'btn btn-primary' %>
    <% else %>
      <%= form.submit t('save'), class: 'btn btn-primary' %>
      <%= link_to t('cancel'), organization_path(@organization), class: 'btn btn-secondary' %>
    <% end %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>">
  <p>
    <strong>Member:</strong>
    <%= income.membership.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= income.amount %>
  </p>

</div>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render "form", income: @income %>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<h1><%= t('add_income') %></h1>

<%= render "form", income: @income %>

app/views/incomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_organization_income_path(@organization, @income) %> |
  <%= link_to "Back to incomes", organization_incomes_path(@organization) %>

  <%= button_to "Destroy this income", organization_income_url(@organization, @income), method: :delete %>
</div>