config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'healthcheck', to: 'healthcheck#show'

  resources :organizations do
    resources :transactions
    resources :incomes
    resources :expenses
    resources :memberships
  end

  devise_for :users
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, class_name: 'User'
  has_many :transactions, dependent: :destroy

  scope :with_member, ->(user) { joins(:memberships).where(memberships: { user_id: user.id }) }

  def member?(user) = memberships.exists?(member: user)
  def owner = members.find_by(memberships: { role: :owner })
  def owner?(user) = user == owner

  def balance = transactions.sum(:amount)
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]

  # GET /organizations or /organizations.json
  def index
    authorize :organization
    @organizations = policy_scope(Organization)
  end

  # GET /organizations/1 or /organizations/1.json
  def show
    authorize @organization
    @memberships = policy_scope @organization.memberships
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    authorize @organization
  end

  # GET /organizations/1/edit
  def edit
    authorize @organization
  end

  # POST /organizations or /organizations.json
  def create
    Create.new(
      context: self,
      organization_params:
    ).call
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    authorize @organization

    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: t('organization_updated') }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    authorize @organization

    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: t('organization_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = policy_scope(Organization).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div class="row">
    <div class="col col-lg-5">
      <%= form_with(model: organization) do |form| %>
        <% if organization.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

            <ul>
              <% organization.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.submit t('create'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
</div>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Name:</strong>
    <%= organization.name %>
  </p>

</div>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render "form", organization: @organization %>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('organizations').capitalize %></h1>

<div id="organizations">
  <% @organizations.each do |organization| %>
    <div class="card mb-3" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= link_to organization.name, organization_path(organization) %></h5>
        <p class="card-text"></p>
        <%= link_to t('enter'), organization_path(organization), class: 'card-link' %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to t('new_organization'), new_organization_path, class: 'btn btn-primary' %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render "form", organization: @organization %>

app/views/organizations/show.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mt-0">
  <div class="col">

    <div class="card">
      <div class="card-body">
        <h5 class="card-title organization__balance"><%= number_to_currency(@organization.balance) %></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= link_to t("transactions"), organization_transactions_url(@organization), class: 'link-secondary' %></h6>
        <p class="card-text">
        </p>
        <div class="btn-group">
        <% if policy(:income).create?(@organization) %>
          <%= link_to new_organization_income_path(@organization), class: 'btn btn-outline-primary' do %>
            <i class="bi bi-piggy-bank"></i>
            <%= t('add_income') %>
          <% end %>
        <% end %>

        <% if policy(:expense).create?(@organization) %>
          <%= link_to new_organization_expense_path(@organization), class: 'btn btn-outline-danger' do %>
            <i class="bi bi-credit-card"></i>
            <%= t('add_expense') %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <i class="bi bi-people-fill"></i>
          <%= t('members').capitalize %>
          <span class="badge bg-secondary"><%= @organization.members.size %></span>
        </h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= link_to t('members'), organization_memberships_url(@organization), class: 'link-secondary' %></h6>
        <p class="card-text">Добавьте участников организации, чтобы дать им возможность следить за показателями орагнизации</p>
        <% if policy(@organization).add_member? %>
          <%= link_to new_organization_membership_path(@organization), class: 'btn btn-outline-primary' do %>
            <i class="bi bi-person-add"></i>
            <%= t('add_member') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<h2><%= t("recent_events").titleize %></h2>

<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-credit-card"></i>
        Подарок преподавателю
      </h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">3500 руб.</p>
    <small></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-credit-card"></i>
        Покупака карандашей
      </h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">100 руб.</p>
    <small></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-person-add"></i>
        Иван Петров
      </h5>
      <small class="text-body-secondary">3 days ago</small>
    </div>
    <p class="mb-1">Инна добавила Ивана Петрова</p>
    <small class="text-body-secondary"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-credit-card"></i>
        Подарок преподавателю
      </h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">3500 руб.</p>
    <small></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-credit-card"></i>
        Покупака карандашей
      </h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">100 руб.</p>
    <small></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <i class="bi bi-person-add"></i>
        Иван Петров
      </h5>
      <small class="text-body-secondary">3 days ago</small>
    </div>
    <p class="mb-1">Инна добавила Ивана Петрова</p>
    <small class="text-body-secondary"></small>
  </a>
</div>